---
- name: DOWNLOAD FILE
  hosts: ubt01
  become: yes
  tasks:
   -  name: Download file to remote server.
      ansible.builtin.get_url:
        url: '{{ item }}'
        dest: /home/techwithnc/
      with_items: ["https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz", "https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.darwin-amd64.tar.gz"]





