---
- name: Install Software for Linux
  hosts: all 
  become: yes
  tasks:
    - name: install net-tools and nmap
      package:
        - net-tools
        - nmap
      state: latest
      update_cache: yes