---
- name: UNARCHIVE
  hosts: 192.168.100.97
  become: yes
  tasks:
  - name: UNARCHIVE FILE ON REMOTE SERVER
    unarchive:
      src: /home/nyeinchan/dir02tarfile.tgz
      dest: /home/nyeinchan/dir01/
      remote_src: yes
