---
- name: install software
  hosts: ubt01
  become: yes
  tasks:
    - name: Installation (Ubuntu)
      ansible.builtin.apt:
        pkg: 
          - net-tools
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Installation (Centos)
      ansible.builtin.yum: 
        update_cache: yes
        name:
            - net-tools
            - nmap
        state: latest
      when: ansible_distribution == "CentOS"