---
- name: Remote file and directory
  hosts: ubt01
  become: yes
  tasks:
  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /home/techwithnc/file01
      state: absent

  - name: Recursively remove directory
    ansible.builtin.file:
      path: /home/techwithnc/dir01
      state: absent

