---
- name: systemd unit
  hosts: ubt01
  become: yes
  tasks:
  - name: systemd unit
    ansible.builtin.systemd:
      name: node_exporter.service
      daemon_reload: true
      enabled: true
      state: started