---
- name: create file
  hosts: ubt01
  become: yes
  tasks:
  - name: create file
    ansible.builtin.shell: |
      cat <<EOF | sudo tee /etc/systemd/system/node_exporter.service
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target
      EOF